# Generated by Django 5.1.4 on 2024-12-13 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmsmodule_document_repository', '0004_alter_documentmodel_folder'),
        ('iam_role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowProtocolModel',
            fields=[
                ('protocol_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('protocol_name', models.CharField(max_length=150)),
                ('protocol_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Process',
                'db_table': 'Protocol',
                'ordering': ['protocol_name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStageModel',
            fields=[
                ('approval_stage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_level', models.PositiveIntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_approval_stages', to='iam_role.iamrolemodel')),
            ],
            options={
                'db_table': 'Approval_Level',
                'ordering': ['stage_level'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedRequestByRequestOwnerModel',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.approvalstagemodel')),
                ('file_for_approval', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentversionmodel')),
                ('request_assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_to_requests', to=settings.AUTH_USER_MODEL)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_approved', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_approved', to='workflow_manager.workflowprotocolmodel')),
            ],
            options={
                'verbose_name': 'Approved',
                'db_table': 'Approved_Requests',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='approvalstagemodel',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_approval_stages', to='workflow_manager.approvedrequestbyrequestownermodel'),
        ),
        migrations.CreateModel(
            name='WorkFlowActionsModel',
            fields=[
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_name', models.CharField(max_length=150)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('action_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow_manager.workflowprotocolmodel')),
            ],
            options={
                'verbose_name': 'Action',
                'db_table': 'Actions',
                'ordering': ['action_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlowStateModel',
            fields=[
                ('state_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_description', models.TextField(max_length=255, null=True)),
                ('state_in_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow_manager.workflowprotocolmodel')),
            ],
            options={
                'verbose_name': 'State',
                'db_table': 'States',
                'db_table_comment': 'State table in the workflow',
                'ordering': ['state_name'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='UnApprovedRequestByOwnerModel',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.approvalstagemodel')),
                ('file_for_approval', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentversionmodel')),
                ('request_assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_requests_unapproved', to=settings.AUTH_USER_MODEL)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_unapproved', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_unapproved', to='workflow_manager.workflowprotocolmodel')),
                ('approval_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_approved', to='workflow_manager.workflowstatemodel')),
            ],
            options={
                'verbose_name': 'UnApproved',
                'db_table': 'UnApproved_Requests',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IntermediateRequestModel',
            fields=[
                ('intermediate_request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=255)),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('request_recieved_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='workflow_manager.approvedrequestbyrequestownermodel')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam_role.iamrolemodel')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_requests', to='workflow_manager.approvalstagemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.workflowstatemodel')),
            ],
            options={
                'db_table': 'Intermediate_Request',
                'ordering': ['request_recieved_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedRequestsModel',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.approvalstagemodel')),
                ('file_for_approval', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentversionmodel')),
                ('request_assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_to_requests', to=settings.AUTH_USER_MODEL)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_requests_approved', to='workflow_manager.workflowprotocolmodel')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_state_approved', to='workflow_manager.workflowstatemodel')),
            ],
            options={
                'verbose_name': 'Final_Approved',
                'db_table': 'Final_Approved_Requests',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='approvedrequestbyrequestownermodel',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_approved', to='workflow_manager.workflowstatemodel'),
        ),
        migrations.CreateModel(
            name='WorkFlowTransitionModel',
            fields=[
                ('transition_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_action', to='workflow_manager.workflowactionsmodel')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from_state', to='workflow_manager.workflowstatemodel')),
                ('protocol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_protocol', to='workflow_manager.workflowprotocolmodel')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to_state', to='workflow_manager.workflowstatemodel')),
            ],
            options={
                'verbose_name': 'Transition',
                'db_table': 'Transition',
                'ordering': ['transition_name'],
            },
        ),
        migrations.AddField(
            model_name='approvalstagemodel',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.workflowtransitionmodel'),
        ),
        migrations.CreateModel(
            name='ApprovalStageTemplateModel',
            fields=[
                ('stage_template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_stage_templates', to='iam_role.iamrolemodel')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='workflow_manager.workflowprotocolmodel')),
            ],
            options={
                'ordering': ['stage_name'],
                'unique_together': {('process', 'stage_name')},
            },
        ),
    ]
