# Generated by Django 5.0.6 on 2024-08-11 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowProtocolModel',
            fields=[
                ('protocol_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('protocol_name', models.CharField(max_length=150)),
                ('protocol_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Process',
                'db_table': 'Protocol',
                'ordering': ['protocol_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlowActionsModel',
            fields=[
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_name', models.CharField(max_length=150)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('action_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow_manager.workflowprotocolmodel')),
            ],
            options={
                'verbose_name': 'Action',
                'db_table': 'Actions',
                'ordering': ['action_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlowStateModel',
            fields=[
                ('state_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_description', models.TextField(max_length=255, null=True)),
                ('state_in_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow_manager.workflowprotocolmodel')),
            ],
            options={
                'verbose_name': 'State',
                'db_table': 'States',
                'db_table_comment': 'State table in the workflow',
                'ordering': ['state_name'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowTransitionModel',
            fields=[
                ('transition_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_action', to='workflow_manager.workflowactionsmodel')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from_state', to='workflow_manager.workflowstatemodel')),
                ('protocol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_protocol', to='workflow_manager.workflowprotocolmodel')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to_state', to='workflow_manager.workflowactionsmodel')),
            ],
            options={
                'verbose_name': 'Transition',
                'db_table': 'Transition',
                'ordering': ['transition_name'],
            },
        ),
    ]
