# Generated by Django 5.0.6 on 2024-08-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtransitionmodel',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to_state', to='workflow_manager.workflowstatemodel'),
        ),
    ]
