# Generated by Django 5.0.6 on 2024-09-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_role', '0003_alter_iamrolemodel_role_id'),
        ('workflow_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediaterequestmodel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam_role.iamrolemodel'),
        ),
    ]
