# Generated by Django 5.0.6 on 2024-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstagetemplatemodel',
            name='stage_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
