# Generated by Django 5.0.6 on 2024-08-11 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0002_alter_workflowtransitionmodel_to_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInWorkFlowModel',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='workflow_manager.workflowstatemodel')),
                ('request_assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_request', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_protocol', to='workflow_manager.workflowprotocolmodel')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WorkFlow_Requests',
                'db_table': 'WorkFlow_Request',
                'ordering': ['title'],
            },
        ),
    ]
