# Generated by Django 5.0.6 on 2024-08-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0002_approvalstagetemplatemodel_stage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalstagemodel',
            options={'ordering': ['stage_level']},
        ),
    ]
