# Generated by Django 5.0.6 on 2024-08-31 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_role', '0002_iamrolemodel_users'),
        ('workflow_manager', '0003_alter_approvalstagemodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateRequestModel',
            fields=[
                ('intermediate_request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=255)),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('request_recieved_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='workflow_manager.approvedrequestbyrequestownermodel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam_role.iamrolemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Intermediate_Request',
                'ordering': ['request_recieved_at'],
            },
        ),
    ]
