# Generated by Django 5.0.6 on 2024-08-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0004_intermediaterequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediaterequestmodel',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.workflowstatemodel'),
        ),
    ]
