# Generated by Django 5.0.6 on 2024-09-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0009_intermediaterequestmodel_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediaterequestmodel',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_requests', to='workflow_manager.approvalstagemodel'),
        ),
    ]
