# Generated by Django 5.0.6 on 2024-09-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0012_intermediaterequestmodel_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediaterequestmodel',
            name='approved_by',
        ),
    ]
