# Generated by Django 5.0.6 on 2024-09-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0013_remove_intermediaterequestmodel_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstagemodel',
            name='assigned_user',
        ),
    ]
