# Generated by Django 5.0.6 on 2024-09-08 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('folder_identifier', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_created_date', models.DateTimeField(auto_now_add=True)),
                ('folder_updated_date', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolder', to='dmsmodule_folder.foldermodel')),
            ],
            options={
                'verbose_name': 'Folders',
                'db_table': 'Folders',
                'db_table_comment': 'Folder table for DMS',
                'ordering': ['folder_name'],
                'base_manager_name': 'objects',
            },
        ),
    ]
