# Generated by Django 5.0.6 on 2024-07-25 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmsmodule_folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocumentModel',
            fields=[
                ('uploaded_document_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_document_name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='pdf_files/')),
                ('uploaded_file_date', models.DateTimeField(auto_now_add=True)),
                ('updated_file_date', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dmsmodule_folder.foldermodel')),
            ],
            options={
                'verbose_name': 'upload',
                'db_table': 'Upload_Document',
                'db_table_comment': 'Uploaded document table DMS',
                'ordering': ['uploaded_document_name'],
                'base_manager_name': 'objects',
            },
        ),
    ]
