# Generated by Django 5.0.6 on 2024-09-09 14:41

import django.db.models.deletion
import dmsmodule.helper.file_extension_validator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmsmodule_folder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInformation',
            fields=[
                ('document_information_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'Document_Information',
                'db_table_comment': 'document table DMS',
                'ordering': ['document_name'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('document_version_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('document_name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='pdf_files/', validators=[dmsmodule.helper.file_extension_validator.FileExtensionValidator(extensions=['.docx', '.xlsx', '.ppt', '.pdf'])])),
                ('uploaded_file_date', models.DateTimeField(auto_now_add=True)),
                ('updated_file_date', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_information', to='dmsmodule_file_mangement.documentinformation')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dmsmodule_folder.foldermodel')),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'Document_Version',
                'db_table_comment': 'Uploaded document table DMS',
                'ordering': ['document_name'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='documentinformation',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_document', to='dmsmodule_file_mangement.documentversion'),
        ),
    ]
