# Generated by Django 5.0.6 on 2024-09-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmsmodule_file_mangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentversion',
            options={'base_manager_name': 'objects', 'ordering': ['document_name'], 'verbose_name': 'Upload'},
        ),
    ]
