# Generated by Django 5.0.6 on 2024-08-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsmodule_file_mangement', '0001_initial'),
        ('dmsmodule_folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocumentmodel',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dmsmodule_folder.foldermodel'),
        ),
    ]
