# Generated by Django 5.0.6 on 2024-09-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsmodule_file_mangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_information', to='dmsmodule_file_mangement.documentinformation'),
        ),
    ]
