# Generated by Django 5.0.6 on 2024-10-27 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationModel',
            fields=[
                ('delegation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delegation_start_date', models.DateTimeField(blank=True, null=True)),
                ('delegation_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_delegation_active', models.BooleanField(default=True)),
                ('delegatee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegatee', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
