# Generated by Django 5.1.4 on 2024-12-13 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationModel',
            fields=[
                ('delegation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delegation_start_date', models.DateTimeField(blank=True, null=True)),
                ('delegation_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_delegation_active', models.BooleanField(default=True)),
            ],
        ),
    ]
