# Generated by Django 5.1.4 on 2024-12-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delegationmodel',
            name='delegatee_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegatee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegationmodel',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL),
        ),
    ]
