# Generated by Django 5.0.6 on 2024-07-10 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posixgroupusermodel',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='useraccount_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
