# Generated by Django 5.1.4 on 2025-02-08 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('machine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MachineRecord',
            fields=[
                ('record_identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('record_new', models.DecimalField(decimal_places=3, max_digits=15)),
                ('record_previous', models.DecimalField(decimal_places=3, max_digits=15)),
                ('record_created_at', models.DateTimeField(auto_now=True)),
                ('record_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Records',
                'ordering': ['record_created_at'],
            },
        ),
    ]
