# Generated by Django 5.1.4 on 2025-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinemodel',
            options={'ordering': ['machine_name']},
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='new_record',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='previous_record',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='sold_qty',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterModelTable(
            name='machinemodel',
            table='Machine',
        ),
    ]
