# Generated by Django 5.1.4 on 2025-02-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taf', '0002_alter_machinemodel_options_machinemodel_new_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinemodel',
            name='sold_qty',
        ),
    ]
