# Generated by Django 5.0.6 on 2024-09-23 13:40

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IamRoleModel',
            fields=[
                ('role_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(max_length=100)),
                ('role_description', models.TextField(blank=True, max_length=255, null=True)),
                ('role_scope', models.CharField(blank=True, max_length=150, null=True)),
                ('role_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deprecated', 'deprecated')], default='active', max_length=150)),
                ('role_created_at', models.DateTimeField(auto_now=True)),
                ('role_modified_date', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Role',
                'ordering': ['role_name'],
            },
        ),
    ]
