# Generated by Django 5.1.4 on 2025-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_policy', '0001_initial'),
        ('iam_role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamrolemodel',
            name='policies',
            field=models.ManyToManyField(related_name='roles', to='iam_policy.oromialandpolicy'),
        ),
    ]
