# Generated by Django 5.0.6 on 2024-10-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_policy', '0003_rename_description_oromialandpolicy_policy_description_and_more'),
        ('iam_role', '0002_iamrolemodel_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamrolemodel',
            name='policies',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to='iam_policy.oromialandpolicy'),
        ),
    ]
