# Generated by Django 5.0.6 on 2024-09-09 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_role', '0002_iamrolemodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamrolemodel',
            name='role_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
