# Generated by Django 5.0.6 on 2024-12-08 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam_role', '0003_alter_iamrolemodel_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProcessTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(help_text='Name of the workflow protocol (e.g., Document Approval).', max_length=150)),
                ('protocol_type', models.CharField(choices=[('document', 'Document Approval'), ('leave', 'Leave Approval'), ('expense', 'Expense Approval'), ('custom', 'Custom Approval')], default='custom', help_text='Type of approval process (e.g., document, leave, expense).', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this protocol is currently active.')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the approval process.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStepModel',
            fields=[
                ('step_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='attribute to identify each step ', primary_key=True, serialize=False)),
                ('stage_name', models.CharField(help_text='Name of the approval stage.', max_length=100)),
                ('stage_order', models.PositiveIntegerField(default=1, help_text='Sequence number of this stage in the process.')),
                ('allow_delegate', models.BooleanField(default=False, help_text='Whether to allow delegated approvers for this stage.')),
                ('criteria', models.JSONField(blank=True, help_text='Conditions for a record to enter this stage.', null=True)),
                ('routing_type', models.CharField(choices=[('Unanimous', 'Unanimous Approval'), ('FirstResponse', 'First Response')], default='Unanimous', help_text='Specifies how to handle approval/rejection when multiple approvers are assigned.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this approval stage.', null=True)),
                ('reject_behavior', models.CharField(blank=True, help_text='Behavior when a request is rejected during this stage.', max_length=50, null=True)),
                ('process', models.ForeignKey(help_text='Approval process to which this stage belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='workflow_approval_process.approvalprocesstypemodel')),
                ('role', models.ForeignKey(help_text='Role responsible for approving this stage.', on_delete=django.db.models.deletion.CASCADE, related_name='role_stage', to='iam_role.iamrolemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStepApprovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.ForeignKey(help_text='User assigned as an approver for this stage.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_stages', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(help_text='Approval stage to which these approvers are assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='workflow_approval_process.approvalstepmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalEntryCriteriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_filter', models.CharField(blank=True, help_text="Filter logic for criteria items (e.g., '(1 AND 2) OR 3').", max_length=255, null=True)),
                ('formula', models.TextField(blank=True, help_text='Formula that must evaluate to true for a record to enter this stage.', null=True)),
                ('stage', models.ForeignKey(help_text='Approval stage associated with this entry criteria.', on_delete=django.db.models.deletion.CASCADE, related_name='entry_criteria', to='workflow_approval_process.approvalstepmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowActionModel',
            fields=[
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_name', models.CharField(max_length=150)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('action_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow_approval_process.approvalprocesstypemodel')),
            ],
            options={
                'ordering': ['action_name'],
            },
        ),
        migrations.AddField(
            model_name='approvalstepmodel',
            name='approval_action',
            field=models.ForeignKey(blank=True, help_text='Action to perform when this stage is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_stage_actions', to='workflow_approval_process.workflowactionmodel'),
        ),
        migrations.AddField(
            model_name='approvalstepmodel',
            name='rejection_action',
            field=models.ForeignKey(blank=True, help_text='Action to perform when this stage is rejected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_stage_actions', to='workflow_approval_process.workflowactionmodel'),
        ),
        migrations.CreateModel(
            name='WorkflowStateModel',
            fields=[
                ('state_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_description', models.TextField(max_length=255, null=True)),
                ('state_in_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow_approval_process.approvalprocesstypemodel')),
            ],
            options={
                'db_table_comment': 'State table in the workflow',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowProcessTransitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_action', to='workflow_approval_process.workflowactionmodel')),
                ('protocol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_protocol', to='workflow_approval_process.approvalprocesstypemodel')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from_state', to='workflow_approval_process.workflowstatemodel')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to_state', to='workflow_approval_process.workflowstatemodel')),
            ],
        ),
    ]
