# Generated by Django 5.0.6 on 2024-12-08 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_role', '0003_alter_iamrolemodel_policies'),
        ('workflow_approval_process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalstepmodel',
            old_name='criteria',
            new_name='entryCriteria',
        ),
        migrations.RemoveField(
            model_name='approvalstepmodel',
            name='role',
        ),
        migrations.AddField(
            model_name='approvalstepmodel',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, help_text='Role responsible for approving this stage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approver', to='workflow_approval_process.approvalstepapprovers'),
        ),
        migrations.AlterField(
            model_name='approvalstepmodel',
            name='process',
            field=models.ForeignKey(help_text='Approval process to which this stage belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='workflow_approval_process.approvalprocesstypemodel'),
        ),
        migrations.AlterField(
            model_name='approvalstepmodel',
            name='step_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='attribute to identify each step', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ApprovalProcessModel',
            fields=[
                ('process_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Approval Process', primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('allow_recall', models.BooleanField(default=False)),
                ('allowed_submitter', models.ManyToManyField(help_text='Roles allowed to submit records for this approval process', related_name='approval_process_roles', to='iam_role.iamrolemodel')),
            ],
        ),
    ]
