# Generated by Django 5.0.6 on 2024-12-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_approval_process', '0002_rename_criteria_approvalstepmodel_entrycriteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalprocessmodel',
            name='allowed_submitter',
        ),
        migrations.AddField(
            model_name='approvalprocessmodel',
            name='entry_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_criteria', to='workflow_approval_process.approvalentrycriteriamodel'),
        ),
        migrations.AddField(
            model_name='approvalprocessmodel',
            name='final_approval_record_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalprocessmodel',
            name='final_rejection_record_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalprocessmodel',
            name='record_editability',
            field=models.CharField(choices=[('AdminOnly', 'AdminOnly'), ('AdminOrCurrentApprover', 'AdminOrCurrentApprover')], default='AdminOnly', max_length=50),
        ),
        migrations.AddField(
            model_name='approvalprocessmodel',
            name='show_approval_history',
            field=models.BooleanField(default=True),
        ),
    ]
