# Generated by Django 5.0.6 on 2024-12-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_approval_process', '0003_remove_approvalprocessmodel_allowed_submitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstepmodel',
            name='process',
            field=models.ForeignKey(help_text='Approval process to which this stage belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='workflow_approval_process.approvalprocessmodel'),
        ),
    ]
