# Generated by Django 5.0.6 on 2024-12-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_approval_process', '0004_alter_approvalstepmodel_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstepmodel',
            name='routing_type',
        ),
        migrations.AddField(
            model_name='approvalstepapprovers',
            name='routing_type',
            field=models.CharField(choices=[('Unanimous', 'Unanimous'), ('FirstResponse', 'FirstResponse')], default='Unanimous', help_text='Specifies how to handle approval/rejection when multiple approvers are assigned.', max_length=50),
        ),
    ]
