# Generated by Django 5.1.4 on 2024-12-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_approval_process', '0005_remove_approvalstepmodel_routing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstepmodel',
            name='approval_action',
        ),
        migrations.RemoveField(
            model_name='approvalstepmodel',
            name='reject_behavior',
        ),
        migrations.RemoveField(
            model_name='approvalstepmodel',
            name='rejection_action',
        ),
        migrations.AddField(
            model_name='approvalstepapprovers',
            name='type',
            field=models.CharField(blank=True, choices=[('adhoc', 'Manual Selection'), ('user', 'Specific User'), ('userHierarchyField', 'User Hierarchy Field'), ('relatedUserField', 'Related User Field'), ('queue', 'Queue')], help_text='Type of approver (e.g., adhoc, user). Determines how the approver is selected.', max_length=50, null=True),
        ),
    ]
