# Generated by Django 5.1.4 on 2025-04-19 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTrackerModel',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_data', models.JSONField(blank=True, null=True)),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('mfa', 'Multi-Factor'), ('sso', 'Single Sign-On'), ('token', 'Token'), ('biometric', 'Biometric')], max_length=20)),
                ('auth_level', models.PositiveSmallIntegerField(default=1)),
                ('mfa_factors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('suspicious', 'Suspicious')], default='active', max_length=20)),
                ('termination_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('impersonator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user'], name='iam_auditin_user_id_4df563_idx'), models.Index(fields=['status'], name='iam_auditin_status_7cf120_idx'), models.Index(fields=['start_time'], name='iam_auditin_start_t_bb753c_idx'), models.Index(fields=['ip_address'], name='iam_auditin_ip_addr_5ff4c3_idx')],
            },
        ),
    ]
