# Generated by Django 5.1.4 on 2025-04-19 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_auditing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontrackermodel',
            name='session_id',
            field=models.CharField(default=datetime.datetime(2025, 4, 19, 21, 3, 51, 281036, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
