# Generated by Django 5.1.4 on 2025-04-21 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_auditing', '0002_sessiontrackermodel_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActivityModel',
            fields=[
                ('session_activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity_started_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('authentication', 'Authentication'), ('access', 'Resource Access'), ('action', 'User Action'), ('security', 'Security Event')], max_length=20)),
                ('activity_details', models.JSONField()),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='iam_auditing.sessiontrackermodel')),
            ],
            options={
                'verbose_name_plural': 'Session Activities',
                'ordering': ['-activity_started_at'],
            },
        ),
    ]
