# Generated by Django 5.0.6 on 2024-08-11 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountsModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_account_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('home_directory', models.CharField(blank=True, max_length=255, null=True)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('account_modified_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Account',
                'db_table': 'User',
                'ordering': ['username'],
            },
        ),
    ]
