# Generated by Django 5.1.4 on 2024-12-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('iam_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountsmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to='iam_groups.posixgroupusermodel'),
        ),
    ]
