# Generated by Django 5.0.6 on 2024-10-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountsmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
