# Generated by Django 5.1.4 on 2024-12-13 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventTypeModel',
            fields=[
                ('eventType_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('eventType_name', models.CharField(max_length=100, unique=True)),
                ('default_channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], default='in_app', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('default_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('notification_read', models.BooleanField(default=False)),
                ('notification_received_at', models.DateTimeField(auto_now_add=True)),
                ('notification_metadata', models.JSONField(blank=True, null=True)),
                ('notification_recepient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
                ('notification_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('notification_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notificationeventtypemodel')),
            ],
            options={
                'db_table': 'Notifications',
                'ordering': ['notification_recepient'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferenceModel',
            fields=[
                ('preference_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('preffered_channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], default='in_app', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='notification.notificationeventtypemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NotificationPreferenceModel',
                'unique_together': {('user', 'template')},
            },
        ),
    ]
