# Generated by Django 5.0.6 on 2024-08-25 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('notification_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification_message', models.TextField()),
                ('notification_read', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(auto_now_add=True)),
                ('notification_status', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_metadata', models.JSONField(blank=True, null=True)),
                ('notification_recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notifications',
                'ordering': ['-notification_sent_at'],
            },
        ),
    ]
