# Generated by Django 5.0.6 on 2024-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_type',
            field=models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('In_app', 'In_app')], default='In_app', max_length=50),
        ),
    ]
