# Generated by Django 5.0.6 on 2024-11-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'ordering': ['notification_recepient']},
        ),
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='notification_sent_at',
            new_name='notification_received_at',
        ),
    ]
