# Generated by Django 5.0.6 on 2024-08-14 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('workflow_manager', '0004_alter_requestinworkflowmodel_request_assigned_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownotification',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.requestinworkflowmodel'),
        ),
    ]
