# Generated by Django 5.0.6 on 2024-08-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('workflow_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownotification',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.approvedrequestbyrequestownermodel'),
        ),
        migrations.AddField(
            model_name='workflownotification',
            name='workflow_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.workflowstatemodel'),
        ),
    ]
