# Generated by Django 5.0.6 on 2024-11-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notificationmodel_notification_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationeventtypemodel',
            old_name='notification_message',
            new_name='default_message',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_message',
            field=models.TextField(null=True),
        ),
    ]
