# Generated by Django 5.0.6 on 2024-09-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notificationmodel_notification_recepient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='notification_recepient',
        ),
    ]
