# Generated by Django 5.0.6 on 2024-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_notification_message_notificationeventtypemodel_default_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
