# Generated by Django 5.0.6 on 2024-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationmodel_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
