# Generated by Django 5.0.6 on 2024-11-08 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notificationmodel_notification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplateModel',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='notification_message',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='notification_priority',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='notification_status',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notificationtemplatemodel'),
        ),
    ]
