# Generated by Django 5.0.6 on 2024-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notificationpreferencemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplatemodel',
            name='template_channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App')], default='in_app', max_length=10),
        ),
    ]
