# Generated by Django 5.0.6 on 2024-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notificationtemplatemodel_template_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferencemodel',
            name='preffered_channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplatemodel',
            name='template_channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], default='in_app', max_length=10),
        ),
    ]
