# Generated by Django 5.0.6 on 2024-07-25 08:09

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosixGroupUserModel',
            fields=[
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('group_posix_Id', models.IntegerField(blank=True, null=True)),
                ('group_abbreviation', models.CharField(max_length=50)),
                ('group_description', models.CharField(blank=True, max_length=255, null=True)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='useraccount_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posix_Group',
                'db_table': 'PosixGroup',
                'db_table_comment': 'Group table for the user account',
                'ordering': ['group_name'],
                'base_manager_name': 'objects',
            },
        ),
    ]
