# Generated by Django 5.1.4 on 2025-04-02 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posixgroupusermodel',
            name='members',
            field=models.ManyToManyField(related_name='useraccount_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
