# Generated by Django 5.0.6 on 2024-10-12 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAction',
            fields=[
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('policy_action_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ActionModel',
            },
        ),
        migrations.CreateModel(
            name='PolicyModel',
            fields=[
                ('policy_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('policy_verison', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('policy_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'PolicyModel',
                'ordering': ['policy_name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyStatements',
            fields=[
                ('statement_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('effect', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], max_length=10)),
                ('actions', models.ManyToManyField(to='iam_policy.policyaction')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='iam_policy.policymodel')),
            ],
            options={
                'db_table': 'StatementModel',
            },
        ),
    ]
