# Generated by Django 5.1.4 on 2024-12-13 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OromiaLandPolicy',
            fields=[
                ('policy_ormomia_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_description', models.TextField(blank=True, null=True)),
                ('policy_version', models.CharField(max_length=100)),
                ('statements', models.JSONField()),
                ('is_app_level', models.BooleanField(default=False)),
                ('is_model_level', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'OromiaLandPolicy',
            },
        ),
        migrations.CreateModel(
            name='PolicyAction',
            fields=[
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('policy_action_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ActionModel',
            },
        ),
        migrations.CreateModel(
            name='PolicyStatements',
            fields=[
                ('statement_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('effect', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], max_length=10)),
                ('actions', models.ManyToManyField(to='iam_policy.policyaction')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements_test', to='iam_policy.oromialandpolicy')),
            ],
            options={
                'db_table': 'StatementModel',
            },
        ),
    ]
