# Generated by Django 5.0.6 on 2024-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oromialandpolicy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oromialandpolicy',
            name='policy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
