# Generated by Django 5.0.6 on 2024-10-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam_policy', '0002_oromialandpolicy_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oromialandpolicy',
            old_name='description',
            new_name='policy_description',
        ),
        migrations.RenameField(
            model_name='oromialandpolicy',
            old_name='version',
            new_name='policy_version',
        ),
        migrations.RenameField(
            model_name='oromialandpolicy',
            old_name='statements_modifed',
            new_name='statements',
        ),
    ]
