# Generated by Django 5.0.6 on 2024-10-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_policy', '0003_rename_description_oromialandpolicy_policy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oromialandpolicy',
            name='is_app_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oromialandpolicy',
            name='is_model_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='oromialandpolicy',
            table='OromiaLandPolicy',
        ),
    ]
