# Generated by Django 5.0.6 on 2024-09-23 13:40

import dmsmodule.helper.file_extension_validator
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadataModel',
            fields=[
                ('metadata_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Metadata',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('document_information_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('current_version_number', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'Document',
                'db_table_comment': 'document table DMS',
                'ordering': ['document_name'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersionModel',
            fields=[
                ('document_version_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('uploaded_file', models.FileField(upload_to='pdf_files/', validators=[dmsmodule.helper.file_extension_validator.FileExtensionValidator(extensions=['.docx', '.xlsx', '.ppt', '.pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Version',
                'db_table': 'Version',
                'base_manager_name': 'objects',
            },
        ),
    ]
