# Generated by Django 5.0.6 on 2024-09-17 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsmodule_document_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadataModel',
            fields=[
                ('metadata_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('document_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentmodel')),
            ],
            options={
                'db_table': 'Metadata',
                'ordering': ['key'],
            },
        ),
    ]
