# Generated by Django 5.0.6 on 2024-09-23 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmsmodule_document_repository', '0001_initial'),
        ('dmsmodule_folder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='dmsmodule_folder.foldermodel'),
        ),
        migrations.AddField(
            model_name='documentmetadatamodel',
            name='document_metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentmodel'),
        ),
        migrations.AddField(
            model_name='documentversionmodel',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dmsmodule_document_repository.documentmodel'),
        ),
        migrations.AddField(
            model_name='documentversionmodel',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_document', to='dmsmodule_document_repository.documentversionmodel'),
        ),
    ]
