# Generated by Django 5.0.6 on 2024-09-24 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsmodule_document_repository', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRepositoryModel',
            fields=[
                ('repository_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repository_name', models.CharField(blank=True, max_length=255, null=True)),
                ('repository_description', models.TextField(blank=True, max_length=255, null=True)),
                ('repository_document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('repository_created_at', models.DateTimeField(auto_now_add=True)),
                ('repository_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Repository_name',
                'ordering': ['repository_name'],
            },
        ),
    ]
