# Generated by Django 5.0.6 on 2024-09-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsmodule_document_repository', '0002_documentmetadatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmetadatamodel',
            name='document_metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentmodel'),
        ),
    ]
