# Generated by Django 5.0.6 on 2024-10-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsmodule_document_repository', '0003_documentrepositorymodel'),
        ('dmsmodule_folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dmsmodule_folder.foldermodel'),
        ),
    ]
