# Generated by Django 5.1.4 on 2024-12-13 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalEntryCriteriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_filter', models.CharField(blank=True, help_text="Filter logic for criteria items (e.g., '(1 AND 2) OR 3').", max_length=255, null=True)),
                ('formula', models.TextField(blank=True, help_text='Formula that must evaluate to true for a record to enter this stage.', null=True)),
            ],
            options={
                'db_table': 'EntryCriteria',
                'db_table_comment': 'State table in the workflow',
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcessTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(help_text='Name of the workflow protocol (e.g., Document Approval).', max_length=150)),
                ('protocol_type', models.CharField(choices=[('document', 'Document Approval'), ('leave', 'Leave Approval'), ('expense', 'Expense Approval'), ('custom', 'Custom Approval')], default='custom', help_text='Type of approval process (e.g., document, leave, expense).', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this protocol is currently active.')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the approval process.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalProcessModel',
            fields=[
                ('process_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Approval Process', primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('allow_recall', models.BooleanField(default=False)),
                ('final_approval_record_lock', models.BooleanField(default=False)),
                ('final_rejection_record_lock', models.BooleanField(default=False)),
                ('record_editability', models.CharField(choices=[('AdminOnly', 'AdminOnly'), ('AdminOrCurrentApprover', 'AdminOrCurrentApprover')], default='AdminOnly', max_length=50)),
                ('show_approval_history', models.BooleanField(default=True)),
                ('entry_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_criteria', to='workflow.approvalentrycriteriamodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStepApprovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('adhoc', 'Manual Selection'), ('user', 'Specific User'), ('userHierarchyField', 'User Hierarchy Field'), ('relatedUserField', 'Related User Field'), ('queue', 'Queue')], help_text='Type of approver (e.g., adhoc, user). Determines how the approver is selected.', max_length=50, null=True)),
                ('routing_type', models.CharField(choices=[('Unanimous', 'Unanimous'), ('FirstResponse', 'FirstResponse')], default='Unanimous', help_text='Specifies how to handle approval/rejection when multiple approvers are assigned.', max_length=50)),
                ('approver', models.ForeignKey(help_text='User assigned as an approver for this stage.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_stages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStepModel',
            fields=[
                ('step_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='attribute to identify each step', primary_key=True, serialize=False)),
                ('allow_delegate', models.BooleanField(default=False, help_text='Whether to allow delegated approvers for this stage.')),
                ('stage_name', models.CharField(help_text='Approval Step Name', max_length=100)),
                ('stage_order', models.PositiveIntegerField(default=1, help_text='Sequence number of this stage in the process.')),
                ('description', models.TextField(blank=True, help_text='Description of this approval stage.', null=True)),
                ('assigned_approver', models.ForeignKey(blank=True, help_text='Role responsible for approving this stage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approver', to='workflow.approvalstepapprovers')),
                ('entryCriteria', models.ForeignKey(blank=True, help_text='Conditions for a record to enter this stage', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.approvalentrycriteriamodel')),
                ('process', models.ForeignKey(help_text='Approval process to which this stage belongs', on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='workflow.approvalprocessmodel')),
            ],
        ),
        migrations.AddField(
            model_name='approvalstepapprovers',
            name='stage',
            field=models.ForeignKey(help_text='Approval stage to which these approvers are assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='workflow.approvalstepmodel'),
        ),
        migrations.AddField(
            model_name='approvalentrycriteriamodel',
            name='stage',
            field=models.ForeignKey(help_text='Approval stage associated with this entry criteria.', on_delete=django.db.models.deletion.CASCADE, related_name='entry_criteria', to='workflow.approvalstepmodel'),
        ),
        migrations.CreateModel(
            name='ApprovalTemplateModel',
            fields=[
                ('template_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('approvers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='workflow.approvalstepapprovers')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='workflow.approvalprocessmodel')),
            ],
            options={
                'ordering': ['stage_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionModel',
            fields=[
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_name', models.CharField(max_length=150)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('action_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow.approvalprocesstypemodel')),
            ],
            options={
                'ordering': ['action_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowProcessTransitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_action', to='workflow.workflowactionmodel')),
                ('protocol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_protocol', to='workflow.approvalprocesstypemodel')),
            ],
        ),
        migrations.AddField(
            model_name='approvalstepmodel',
            name='approval_transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_transitions', to='workflow.workflowprocesstransitionmodel'),
        ),
        migrations.CreateModel(
            name='WorkflowStateModel',
            fields=[
                ('state_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_description', models.TextField(max_length=255, null=True)),
                ('state_in_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.approvalprocesstypemodel')),
            ],
            options={
                'db_table_comment': 'State table in the workflow',
                'ordering': ['state_name'],
            },
        ),
        migrations.AddField(
            model_name='workflowprocesstransitionmodel',
            name='from_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from_state', to='workflow.workflowstatemodel'),
        ),
        migrations.AddField(
            model_name='workflowprocesstransitionmodel',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to_state', to='workflow.workflowstatemodel'),
        ),
        migrations.CreateModel(
            name='ApprovalRequestModel',
            fields=[
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('approval_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.approvalprocessmodel')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_approved_by', to=settings.AUTH_USER_MODEL)),
                ('request_send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.approvalstepmodel')),
                ('request_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_status', to='workflow.workflowstatemodel')),
            ],
            options={
                'db_table': 'Approval_Request',
                'ordering': ['title'],
            },
        ),
    ]
