# Generated by Django 5.0.6 on 2024-06-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccountsmodel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='useraccountsmodel',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='useraccountsmodel',
            old_name='superuser',
            new_name='is_superuser',
        ),
    ]
