# Generated by Django 5.0.6 on 2024-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_active_useraccountsmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountsmodel',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
