# Generated by Django 5.0.6 on 2024-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccountsmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountsmodel',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
