# Generated by Django 5.1.4 on 2024-12-18 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmsmodule_document_repository', '0004_alter_documentmodel_folder'),
        ('iam_role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalEntryCriteriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_filter', models.CharField(blank=True, help_text="Filter logic for criteria items (e.g., '(1 AND 2) OR 3').", max_length=255, null=True)),
                ('formula', models.TextField(blank=True, help_text='Formula that must evaluate to true for a record to enter this stage.', null=True)),
            ],
            options={
                'verbose_name': 'ApprovalEntryCriteria',
                'db_table': 'ApprovalEntryCriteria',
                'db_table_comment': 'Approval entry criteria table in the workflow',
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcessTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(help_text='Name of the workflow protocol (e.g., Document Approval).', max_length=150)),
                ('protocol_type', models.CharField(choices=[('document', 'Document Approval'), ('leave', 'Leave Approval'), ('expense', 'Expense Approval'), ('custom', 'Custom Approval')], default='custom', help_text='Type of approval process (e.g., document, leave, expense).', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this protocol is currently active.')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the approval process.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ApprovalEntryCriteria',
                'db_table': 'ApprovalProcessType',
                'db_table_comment': 'Approval entry criteria table in the workflow',
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcessModel',
            fields=[
                ('process_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Approval Process', primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('allow_recall', models.BooleanField(default=False)),
                ('final_approval_record_lock', models.BooleanField(default=False)),
                ('final_rejection_record_lock', models.BooleanField(default=False)),
                ('record_editability', models.CharField(choices=[('AdminOnly', 'AdminOnly'), ('AdminOrCurrentApprover', 'AdminOrCurrentApprover')], default='AdminOnly', max_length=50)),
                ('show_approval_history', models.BooleanField(default=True)),
                ('allowed_submitter', models.ManyToManyField(help_text='Roles allowed to submit records for this approval process', related_name='allowed_submitter_roles', to='iam_role.iamrolemodel')),
                ('entry_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_criteria', to='workflow_service.approvalentrycriteriamodel')),
            ],
            options={
                'verbose_name': 'ApprovalProcess',
                'db_table': 'ApprovalProcessTable',
                'db_table_comment': 'Approval Process model',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepModel',
            fields=[
                ('step_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='attribute to identify each step', primary_key=True, serialize=False)),
                ('allow_delegate', models.BooleanField(default=False, help_text='Whether to allow delegated approvers for this stage.')),
                ('stage_name', models.CharField(help_text='Approval Step Name', max_length=100)),
                ('stage_order', models.PositiveIntegerField(default=1, help_text='Sequence number of this stage in the process.')),
                ('description', models.TextField(blank=True, help_text='Description of this approval stage.', null=True)),
                ('entryCriteria', models.ForeignKey(blank=True, help_text='Conditions for a record to enter this stage', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_service.approvalentrycriteriamodel')),
                ('process', models.ForeignKey(help_text='Approval process to which this stage belongs', on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='workflow_service.approvalprocessmodel')),
            ],
            options={
                'verbose_name': 'ApprovalStep',
                'db_table': 'ApprovalStepTable',
                'db_table_comment': 'a table keeps each steps in the workflow',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepApprovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('adhoc', 'Manual Selection'), ('user', 'Specific User'), ('userHierarchyField', 'User Hierarchy Field'), ('relatedUserField', 'Related User Field'), ('queue', 'Queue')], help_text='Type of approver (e.g., adhoc, user). Determines how the approver is selected.', max_length=50, null=True)),
                ('routing_type', models.CharField(choices=[('Unanimous', 'Unanimous'), ('FirstResponse', 'FirstResponse')], default='Unanimous', help_text='Specifies how to handle approval/rejection when multiple approvers are assigned.', max_length=50)),
                ('approver', models.ForeignKey(help_text='User assigned as an approver for this stage.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_stages', to=settings.AUTH_USER_MODEL)),
                ('approver_roles', models.ManyToManyField(blank=True, help_text='Roles allowed to approve this stage.', related_name='role_approvers', to='iam_role.iamrolemodel')),
                ('stage', models.ForeignKey(help_text='Approval stage to which these approvers are assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='workflow_service.approvalstepmodel')),
            ],
            options={
                'verbose_name': 'ApprovalStepApprovers',
                'db_table': 'ApprovalStepApproversTable',
                'db_table_comment': 'a table keeps approvers in the workflow',
                'ordering': ['stage'],
            },
        ),
        migrations.AddField(
            model_name='approvalentrycriteriamodel',
            name='stage',
            field=models.ForeignKey(help_text='Approval stage associated with this entry criteria.', on_delete=django.db.models.deletion.CASCADE, related_name='entry_criteria', to='workflow_service.approvalstepmodel'),
        ),
        migrations.CreateModel(
            name='ApprovalTemplateModel',
            fields=[
                ('template_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('approvers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='workflow_service.approvalstepapprovers')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='workflow_service.approvalprocessmodel')),
            ],
            options={
                'verbose_name': 'ApprovalTemplate',
                'db_table': 'ApprovalTemplateTable',
                'ordering': ['stage_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionModel',
            fields=[
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_name', models.CharField(max_length=150)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('action_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow_service.approvalprocessmodel')),
            ],
            options={
                'ordering': ['action_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowProcessTransitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_action', to='workflow_service.workflowactionmodel')),
                ('protocol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_protocol', to='workflow_service.approvalprocessmodel')),
            ],
        ),
        migrations.AddField(
            model_name='approvalstepmodel',
            name='approval_transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_transitions', to='workflow_service.workflowprocesstransitionmodel'),
        ),
        migrations.CreateModel(
            name='WorkflowStateModel',
            fields=[
                ('state_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_description', models.TextField(max_length=255, null=True)),
                ('state_in_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow_service.approvalprocessmodel')),
            ],
            options={
                'db_table_comment': 'State table in the workflow',
                'ordering': ['state_name'],
            },
        ),
        migrations.AddField(
            model_name='workflowprocesstransitionmodel',
            name='from_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from_state', to='workflow_service.workflowstatemodel'),
        ),
        migrations.AddField(
            model_name='workflowprocesstransitionmodel',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to_state', to='workflow_service.workflowstatemodel'),
        ),
        migrations.CreateModel(
            name='SubmittedRequestForApprovalModel',
            fields=[
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_title', models.CharField(max_length=150)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('approval_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_service.approvalprocessmodel')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_approver', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_service.approvalstepmodel')),
                ('file_for_approval', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentversionmodel')),
                ('request_send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_submitter', to=settings.AUTH_USER_MODEL)),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_request_state', to='workflow_service.workflowstatemodel')),
            ],
            options={
                'verbose_name': 'SubmittedRequest',
                'db_table': 'SubmittedRequestTable',
            },
        ),
        migrations.CreateModel(
            name='SavedRequestModel',
            fields=[
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_title', models.CharField(max_length=150)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('approval_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_service.approvalprocessmodel')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_service.approvalstepmodel')),
                ('file_for_approval', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dmsmodule_document_repository.documentversionmodel')),
                ('request_send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_initiator', to=settings.AUTH_USER_MODEL)),
                ('saved_request_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_state', to='workflow_service.workflowstatemodel')),
            ],
            options={
                'verbose_name': 'SavedRequest',
                'db_table': 'SavedRequest',
                'ordering': ['request_title'],
            },
        ),
    ]
