# Generated by Django 5.1.4 on 2024-12-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApprovalStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time the approval status was updated.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the approval process started.')),
                ('stage_name', models.CharField(max_length=255)),
                ('approvers', models.ManyToManyField(help_text='Approvers assigned to this step in the approval process.', related_name='assigned_states', to='workflow_service.approvalstepapprovers')),
                ('current_state', models.ForeignKey(blank=True, help_text='The status of the request in the approval process.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_service.workflowstatemodel')),
                ('current_step', models.ForeignKey(help_text='The current approval step for this request.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_state_step', to='workflow_service.approvalstepmodel')),
                ('request', models.ForeignKey(help_text='The request being processed in the approval workflow.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_state', to='workflow_service.submittedrequestforapprovalmodel')),
            ],
            options={
                'verbose_name': 'RequestApprovalState',
                'db_table': 'RequestApprovalStateTable',
            },
        ),
    ]
