# Generated by Django 5.1.4 on 2024-12-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0002_alter_approvalstagemodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltemplatemodel',
            name='template_entry_criteria',
            field=models.ForeignKey(blank=True, help_text='Criteria to evaluate before entering this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_criteria', to='workflow_service.approvalentrycriteriamodel'),
        ),
    ]
