# Generated by Django 5.1.4 on 2024-12-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0002_requestapprovalstatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstepmodel',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Role responsible for approving this stage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='workflow_service.submittedrequestforapprovalmodel'),
        ),
        migrations.AlterField(
            model_name='requestapprovalstatemodel',
            name='approvers',
            field=models.ManyToManyField(help_text='Approvers assigned to this step in the approval process', related_name='assigned_states', to='workflow_service.approvalstepapprovers'),
        ),
    ]
