# Generated by Django 5.1.4 on 2024-12-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0003_approvalstepmodel_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="The name of the field to filter on (e.g., 'document_status').", max_length=100)),
                ('operator', models.CharField(choices=[('=', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater Than or Equals'), ('<=', 'Less Than or Equals'), ('IN', 'In'), ('NOT IN', 'Not In')], help_text='The operator for the filter condition.', max_length=10)),
                ('value', models.JSONField(help_text='The value(s) for the condition. Can be a single value or a list.')),
                ('criteria', models.ForeignKey(help_text='The parent entry criteria to which this filter item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='criteria_items', to='workflow_service.approvalentrycriteriamodel')),
            ],
        ),
    ]
