# Generated by Django 5.1.4 on 2024-12-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0003_approvaltemplatemodel_template_entry_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltemplatemodel',
            name='template_entry_criteria',
            field=models.OneToOneField(blank=True, help_text='The criteria required to enter this template stage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_template', to='workflow_service.approvalentrycriteriamodel'),
        ),
    ]
