# Generated by Django 5.1.4 on 2024-12-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0004_filteritemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteritemmodel',
            name='criteria_key',
            field=models.CharField(default=1, help_text='A custom key for referencing this filter item in boolean filters.', max_length=50, unique=True),
        ),
    ]
