# Generated by Django 5.1.4 on 2024-12-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0004_alter_approvaltemplatemodel_template_entry_criteria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalstagemodel',
            options={'ordering': ['request']},
        ),
        migrations.AddField(
            model_name='approvalstagemodel',
            name='approval_stage_approvers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_approvers', to='workflow_service.approvalstepapprovers'),
        ),
    ]
