# Generated by Django 5.1.4 on 2025-01-01 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0005_alter_approvalstagemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('template_identifier', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('template_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Template',
            },
        ),
        migrations.AlterField(
            model_name='approvaltemplatemodel',
            name='stage_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='workflow_service.templatemodel'),
        ),
    ]
