# Generated by Django 5.1.4 on 2024-12-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0005_filteritemmodel_criteria_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filteritemmodel',
            table='FilterItemsModel',
        ),
    ]
