# Generated by Django 5.1.4 on 2025-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_service', '0006_templatemodel_alter_approvaltemplatemodel_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteritemmodel',
            name='field_name',
            field=models.CharField(help_text='The name of the field to filter', max_length=100),
        ),
    ]
